update cmake to correctly detect and link pthread with earlier glibc
glibc before 2.34 did not include pthread, linkage was failing.
use find_package(Threads) instead of find_library(PTHREAD_LIB pthread).

Available in CMake since CMake-3.1 https://cmake.org/cmake/help/latest/module/FindThreads.html

fixes:
    [47/167] Linking CXX executable src/espeak-ng
    FAILED: src/espeak-ng
    : && ../toolchain/bin/host-g++ -march=native -O2 -Wall -pipe -I../toolchain/include -Wno-format-security -DDUMMYOPT -Wl,-rpath,../toolchain/lib -L../toolchain/lib src/CMakeFiles/espeak-ng-bin.dir/espeak-ng.c.o -o src/espeak-ng  -Wl,-rpath,:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::  src/libespeak-ng/libespeak-ng.a  src/speechPlayer/libspeechPlayer.a  -lm  src/ucd-tools/libucd.a && :
    /usr/bin/ld: src/libespeak-ng/libespeak-ng.a(event.c.o): in function `event_init':
    event.c:(.text+0x4c2): undefined reference to `pthread_create'
    /usr/bin/ld: src/libespeak-ng/libespeak-ng.a(event.c.o): in function `event_terminate':
    event.c:(.text+0x82d): undefined reference to `pthread_join'
    /usr/bin/ld: src/libespeak-ng/libespeak-ng.a(fifo.c.o): in function `fifo_init':
    fifo.c:(.text+0x70a): undefined reference to `pthread_create'
    /usr/bin/ld: src/libespeak-ng/libespeak-ng.a(fifo.c.o): in function `fifo_terminate':
    fifo.c:(.text+0xb49): undefined reference to `pthread_join'
    collect2: error: ld returned 1 exit status